Renaming tables
FITTY-APP/Fitty-Backend-App pull request #28
Opened 2023-11-12 07:45 UTC by dicohy27

어질어질

2023-11-15 11:20 UTC, uuccu requested changes

2023-11-15 11:20 UTC, uuccu commented on src/main/resources/db/changelog/changelog-0007.yml
> +                  name: exercise_exercise_record_id
왜 체인지로그를 5,6,7로 나눠서 진행한건가요?

2023-11-15 11:20 UTC, uuccu commented on src/main/kotlin/fittibackendapp/exception/NotFoundExerciseSetRecordException.kt
> +    reasonMessage = "존재하지 않는 운동 세트 기록 입니다.",
2가 종목이고 3이 세트아님? 뭔가 이상한뎅

2023-11-15 11:20 UTC, uuccu commented on src/main/kotlin/fittibackendapp/exception/NotFoundExerciseSessionRecordException.kt
>  )
3이 세트고 2가 종목아님?

2023-11-15 11:20 UTC, uuccu commented on src/main/kotlin/fittibackendapp/dto/ExerciseSessionRecordDto.kt
>      val user: UserDto,
음 
1 -> session
2 -> exercise
3 -> set
인거 맞는거지?

2023-11-15 11:20 UTC, uuccu commented on src/main/resources/db/changelog/changelog-0005.yml
> +            newTableName: diet_food_record
테이블 네이밍을 바꿨으면 fk column 네임도 바꿔야 할탠데 (아래 그림 말하는거임)
 테이블 생성하는 브랜치에서 할려고 하는거야? 
 
<img width="376" alt="image" src="https://github.com/FITTI-APP/Fitti-Backend-App/assets/37656369/e1c248fb-634b-401d-b16d-a7ea78d588b8">

만약 그렇다면 이 브랜치에서 이부분은 삭제해야 할듯.

2023-11-15 13:37 UTC, dicohy27 commented on src/main/resources/db/changelog/changelog-0007.yml
> +                  name: exercise_exercise_record_id
일단 체인지로그 5번은 테이블 이름만 바꾸는거라 문제없이 잘 됨
6번부터 외래키 컬럼 명 바꾸려고 한건데
renameColumn했는데 안됨 -> 6번 체인지로그에서 dropForeignKeyConstraint되는지 시도 해본건데 적용돼버림 -> 7번 나머지 작업 이어서 함
근데 renameColumn은 결국 실패해서 걍 drop하고 add함

2023-11-15 13:40 UTC, dicohy27 commented on src/main/kotlin/fittibackendapp/exception/NotFoundExerciseSetRecordException.kt
> +    reasonMessage = "존재하지 않는 운동 세트 기록 입니다.",
ㅇㅇ똑바로 바꾼건데 파일이름도 바뀌면서 git에서 매칭되는 파일 2개를 잘 못 인식한듯

2023-11-15 13:40 UTC, dicohy27 commented on src/main/kotlin/fittibackendapp/exception/NotFoundExerciseSessionRecordException.kt
>  )
이것도 위 댓글과 마찬가지

2023-11-15 13:41 UTC, dicohy27 commented on src/main/kotlin/fittibackendapp/dto/ExerciseSessionRecordDto.kt
>      val user: UserDto,
ㅇㅇ

2023-11-15 13:42 UTC, dicohy27 commented on src/main/resources/db/changelog/changelog-0005.yml
> +            newTableName: diet_food_record
fk column 네임 바꾸는걸 7번 체인지로그에서 함

2023-11-15 14:10 UTC, uuccu commented on src/main/resources/db/changelog/changelog-0007.yml
> +                  name: exercise_exercise_record_id
아 따로 이렇게 나누게된 이유가 잇나 궁금해서 물어봄. 왜냐하면 이게 스택이다보니까 점점 더러워질수밖에 없어서 깔끔하게 하는게 좋긴하거든. 걍 궁금해서 물어봄

2023-11-15 14:10 UTC, uuccu commented on src/main/kotlin/fittibackendapp/exception/NotFoundExerciseSetRecordException.kt
> +    reasonMessage = "존재하지 않는 운동 세트 기록 입니다.",
그럴수가있남?

2023-11-15 14:10 UTC, uuccu commented on src/main/kotlin/fittibackendapp/exception/NotFoundExerciseSessionRecordException.kt
>  )
이것도 위 댓글과 마찬가지

2023-11-15 14:11 UTC, uuccu commented on src/main/resources/db/changelog/changelog-0005.yml
> +            newTableName: diet_food_record
없는뎅?

2023-11-15 14:12 UTC, dicohy27 commented on src/main/resources/db/changelog/changelog-0007.yml
> +                  name: exercise_exercise_record_id
나도 이렇게 하고 싶진 않았습니닷...이미 좆돼버렸습니닷...!!

2023-11-15 14:15 UTC, dicohy27 commented on src/main/kotlin/fittibackendapp/exception/NotFoundExerciseSetRecordException.kt
> +    reasonMessage = "존재하지 않는 운동 세트 기록 입니다.",
모름ㅋ 사실 내가 븅신인 걸지도 근데 바뀔 애들은 제대로 바껴서 git을 의심해봄ㅋ

2023-11-15 14:15 UTC, dicohy27 commented on src/main/resources/db/changelog/changelog-0005.yml
> +            newTableName: diet_food_record
Rename 안돼서 Drop하고 다시 add함ㅋ

2023-11-15 15:04 UTC, uuccu commented on src/main/resources/db/changelog/changelog-0007.yml
> +                  name: exercise_exercise_record_id
ㅋㅋ 어떻게할래? 정정할래 어쩔래?

2023-11-15 15:05 UTC, uuccu commented on src/main/kotlin/fittibackendapp/exception/NotFoundExerciseSetRecordException.kt
> +    reasonMessage = "존재하지 않는 운동 세트 기록 입니다.",
?

2023-11-15 15:05 UTC, uuccu commented on src/main/resources/db/changelog/changelog-0005.yml
> +            newTableName: diet_food_record
???

2023-11-15 15:07 UTC, dicohy27 commented on src/main/resources/db/changelog/changelog-0007.yml
> +                  name: exercise_exercise_record_id
합치고 싶습니닷...!!!

2023-11-15 15:11 UTC, dicohy27 commented on src/main/resources/db/changelog/changelog-0007.yml
> +                  name: exercise_exercise_record_id
근데 어케 합침? 체인지로그6 적용 된 상태에서 체인지로그 6 바꾸고 다시 실행하면 에러뜨던데

2023-11-15 15:19 UTC, dicohy27 commented on src/main/kotlin/fittibackendapp/exception/NotFoundExerciseSetRecordException.kt
> +    reasonMessage = "존재하지 않는 운동 세트 기록 입니다.",
원래 Notfoundexerciserecord3exception가 쓰이던 부분은 notfoundexercisesetrecordexepcion으로 바뀌었고 notfoundexerciserecord2가 쓰이던 부분은 notfoundexerciseexerciserecord로 바꼈다는 말임 근데 엑셉션을 사용한 부분은 내가 직접 바꾼게 아니라 엑셉션 이름 바꾸면서 자동으로 바뀜 그래서 git이 매칭되는 파일 2개를 잘 못 검사했다고 생각한거임

2023-11-15 15:22 UTC, dicohy27 commented on src/main/resources/db/changelog/changelog-0005.yml
> +            newTableName: diet_food_record
? 내가 질문 잘 못 이해한듯

2023-11-15 15:27 UTC, dicohy27 commented on src/main/resources/db/changelog/changelog-0005.yml
> +            newTableName: diet_food_record
가 아니네 질문 제대로 이해했는데 내가 똑바로 확인 안함 exercise 도메인만 fk 컬럼 수정하고 diet는 깜빡함 내일 하겠음

2023-11-15 16:46 UTC, uuccu commented on src/main/resources/db/changelog/changelog-0007.yml
> +                  name: exercise_exercise_record_id
?
ㅇㅎ 안알려준게있었넹 냥냥!

2023-11-15 16:46 UTC, uuccu commented on src/main/resources/db/changelog/changelog-0007.yml
> +                  name: exercise_exercise_record_id
근데 이것도 필설할수없는 깨달음임 ㅋ . 니또 디코로 개답답해할게 보이는군

2023-11-15 16:46 UTC, uuccu commented on src/main/kotlin/fittibackendapp/exception/NotFoundExerciseSetRecordException.kt
> +    reasonMessage = "존재하지 않는 운동 세트 기록 입니다.",
딜교 개이득 ? 하나로 장문이끌어내기

2023-11-15 16:47 UTC, uuccu commented on src/main/resources/db/changelog/changelog-0005.yml
> +            newTableName: diet_food_record
nope 수정하지마.

2023-11-16 01:16 UTC, dicohy27 commented on src/main/resources/db/changelog/changelog-0007.yml
> +                  name: exercise_exercise_record_id
필설해다오...!

2023-11-16 01:16 UTC, dicohy27 commented on src/main/kotlin/fittibackendapp/exception/NotFoundExerciseSetRecordException.kt
> +    reasonMessage = "존재하지 않는 운동 세트 기록 입니다.",
뒤지실?

2023-11-16 01:17 UTC, dicohy27 commented on src/main/resources/db/changelog/changelog-0005.yml
> +            newTableName: diet_food_record
Nope가 뭐임

2023-11-20 01:48 UTC, uuccu commented on src/main/resources/db/changelog/changelog-0007.yml
> +                  name: exercise_exercise_record_id
암튼 일단 합쳐봄

2023-11-20 02:09 UTC, merged