해당 주의 목표 식단대비 현재 탄단지 비율 api
FITTY-APP/Fitty-Backend-App pull request #44
Opened 2024-01-16 14:22 UTC by xhdtlsid2

2024-01-29 12:57 UTC, uuccu requested changes
리뷰완료........ 너무오랫동안 안해서 까먹음 ㅋㅋㅋ

2024-01-29 12:57 UTC, uuccu commented on src/main/kotlin/fittibackendapp/domain/diet/entity/TargetPcfRatio.kt
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
굳이 테이블을 또 만들이유가 있었음?
정규화를 해치지 않는건가?

2024-01-29 12:57 UTC, uuccu commented on src/main/resources/graphql/domain/diet/query/PcfRatioQuery.gql
> +}
주석 설명있으면 좋을거 같음 ㅎㅎ

2024-01-29 12:57 UTC, uuccu commented on src/main/resources/graphql/domain/diet/query/TargetPcfRatioQuery.gql
> +}
이것도 주석설명 있으면 좋을듯.

2024-01-29 12:57 UTC, uuccu commented on src/main/kotlin/fittibackendapp/domain/diet/facade/DietRecordQueryFacade.kt
>  }
왜 두 파시드 함수가 접근하는 테이블이 다른거임? 
둘다 같은 엔티티로 만들수있는건데 그러면 새로운 비율 테이블을 만들필요가 없던게 아님?
몰라서 물어보는거ㅠ

2024-02-08 13:09 UTC, xhdtlsid2 commented on src/main/kotlin/fittibackendapp/domain/diet/entity/TargetPcfRatio.kt
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
음 테이블 안 만들면 어디에 저장하는게 좋을거같음?
user 테이블에 컬럼 추가할까도 했었는데 거기는 뭔가 계정 관련 정보?들만 모아놓은 것 같아서 일단 따로 만들었음

2024-02-08 13:13 UTC, xhdtlsid2 commented on src/main/resources/graphql/domain/diet/query/PcfRatioQuery.gql
> +}
이름 짓는건 어려워ㅠ

2024-02-08 13:23 UTC, xhdtlsid2 commented on src/main/kotlin/fittibackendapp/domain/diet/facade/DietRecordQueryFacade.kt
>  }
`getPcfRatioInGramsBetweenDays`는 실제로 섭취한 탄단지 양의 비율을 반환하는거라 식단 기록 테이블을 보고
`getTargetPcfRatio`는 목표 탄단지 섭취량 비율을 반환하는거라 목표 탄단지 비율 테이블을 봄
같은 엔티티로 만든다는건 어떤 얘기임?.?

2024-02-08 13:23 UTC, xhdtlsid2 commented on src/main/resources/graphql/domain/diet/query/TargetPcfRatioQuery.gql
> +}
추가완료료

2024-02-08 13:33 UTC, uuccu commented on src/main/kotlin/fittibackendapp/domain/diet/entity/TargetPcfRatio.kt
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
아아아
내가 잘못봤넹. 이거 목표탄단지구나

2024-02-08 13:33 UTC, uuccu commented on src/main/kotlin/fittibackendapp/domain/diet/facade/DietRecordQueryFacade.kt
>  }
아하 
잘못봄

2024-02-08 13:33 UTC, uuccu approved these changes
![Uploading image.png…]()

2024-02-08 13:37 UTC, merged