유저 데이터 입력하기
FITTY-APP/Fitty-Backend-App pull request #64
Opened 2024-04-07 13:06 UTC by dicohy27

ㅇㅇ

2024-04-11 08:39 UTC, uuccu requested changes

2024-04-11 08:39 UTC, uuccu commented on src/main/kotlin/fittibackendapp/domain/body/service/UserDetailService.kt
> +    ): UserDetailDto {
지금 이브랜치에서 DB에 시간대별로 입력해보는거 구현해보자

2024-04-11 08:39 UTC, uuccu commented on src/main/kotlin/fittibackendapp/dto/UserDetailDto.kt
> +)
여기있는 user: UserDto 지우자

2024-04-11 08:39 UTC, uuccu commented on src/main/resources/db/changelog/changelog-0011.yml
> +            tableName: user_detail
여기에 이어서 작성하지 않아도 됨. 
새로 12번 파일 만들어도됨

2024-04-11 08:39 UTC, uuccu commented on src/main/resources/graphql/domain/body/entity/UserDetail.gql
> +}
여기서도 User 지우자.

2024-04-11 08:39 UTC, uuccu commented on src/main/resources/graphql/domain/body/mutation/UserDetailMutation.gql
> +}
주석 설명 제대로 만들자.

2024-04-11 15:14 UTC, dicohy27 commented
ㅇㅋ염

2024-04-16 15:10 UTC, uuccu commented
### Code Coverage
|File|Coverage [0.00%]|
|:-|:-:|
|[src/main/kotlin/fittibackendapp/domain/body/entity/UserDetail.kt](https://github.com/FITTI-APP/Fitti-Backend-App/blob/4636bc199dd79b399596972976a8805ddc82304c/src%2Fmain%2Fkotlin%2Ffittibackendapp%2Fdomain%2Fbody%2Fentity%2FUserDetail.kt)|0.00%|
|[src/main/kotlin/fittibackendapp/domain/body/graphql/mutation/UserDetailMutationMapper.kt](https://github.com/FITTI-APP/Fitti-Backend-App/blob/4636bc199dd79b399596972976a8805ddc82304c/src%2Fmain%2Fkotlin%2Ffittibackendapp%2Fdomain%2Fbody%2Fgraphql%2Fmutation%2FUserDetailMutationMapper.kt)|0.00%|
|[src/main/kotlin/fittibackendapp/domain/body/graphql/mutation/input/PutUserDetailInput.kt](https://github.com/FITTI-APP/Fitti-Backend-App/blob/4636bc199dd79b399596972976a8805ddc82304c/src%2Fmain%2Fkotlin%2Ffittibackendapp%2Fdomain%2Fbody%2Fgraphql%2Fmutation%2Finput%2FPutUserDetailInput.kt)|0.00%|
|[src/main/kotlin/fittibackendapp/domain/body/service/UserDetailService.kt](https://github.com/FITTI-APP/Fitti-Backend-App/blob/4636bc199dd79b399596972976a8805ddc82304c/src%2Fmain%2Fkotlin%2Ffittibackendapp%2Fdomain%2Fbody%2Fservice%2FUserDetailService.kt)|0.00%|
|[src/main/kotlin/fittibackendapp/dto/UserDetailDto.kt](https://github.com/FITTI-APP/Fitti-Backend-App/blob/4636bc199dd79b399596972976a8805ddc82304c/src%2Fmain%2Fkotlin%2Ffittibackendapp%2Fdto%2FUserDetailDto.kt)|0.00%|
|[src/main/kotlin/fittibackendapp/exception/NotFoundUserDetailException.kt](https://github.com/FITTI-APP/Fitti-Backend-App/blob/4636bc199dd79b399596972976a8805ddc82304c/src%2Fmain%2Fkotlin%2Ffittibackendapp%2Fexception%2FNotFoundUserDetailException.kt)|0.00%|

|Total Project Coverage|0.00%|:x:|
|:-|:-:|:-:|

2024-04-22 09:16 UTC, uuccu commented
테스트코드는 신경쓰지말고 PR리뷰 반영부터하삼

2024-04-22 13:47 UTC, dicohy27 commented
반영 했잖음

2024-04-23 12:36 UTC, uuccu approved these changes
반영되어있네. commit 버젼 다르게 봤나봄

2024-04-23 13:03 UTC, merged